# CMake generated Testfile for 
# Source directory: E:/SC17/dhara-master
# Build directory: E:/SC17/dhara-master/build_vs2022
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(all_tests "E:/SC17/dhara-master/build_vs2022/Debug/all_tests.exe")
  set_tests_properties(all_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/SC17/dhara-master/CMakeLists.txt;153;add_test;E:/SC17/dhara-master/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(all_tests "E:/SC17/dhara-master/build_vs2022/Release/all_tests.exe")
  set_tests_properties(all_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/SC17/dhara-master/CMakeLists.txt;153;add_test;E:/SC17/dhara-master/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(all_tests "E:/SC17/dhara-master/build_vs2022/MinSizeRel/all_tests.exe")
  set_tests_properties(all_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/SC17/dhara-master/CMakeLists.txt;153;add_test;E:/SC17/dhara-master/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(all_tests "E:/SC17/dhara-master/build_vs2022/RelWithDebInfo/all_tests.exe")
  set_tests_properties(all_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/SC17/dhara-master/CMakeLists.txt;153;add_test;E:/SC17/dhara-master/CMakeLists.txt;0;")
else()
  add_test(all_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(eflash_ftl_tests "E:/SC17/dhara-master/build_vs2022/Debug/eflash_ftl_tests.exe")
  set_tests_properties(eflash_ftl_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/SC17/dhara-master/CMakeLists.txt;156;add_test;E:/SC17/dhara-master/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(eflash_ftl_tests "E:/SC17/dhara-master/build_vs2022/Release/eflash_ftl_tests.exe")
  set_tests_properties(eflash_ftl_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/SC17/dhara-master/CMakeLists.txt;156;add_test;E:/SC17/dhara-master/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(eflash_ftl_tests "E:/SC17/dhara-master/build_vs2022/MinSizeRel/eflash_ftl_tests.exe")
  set_tests_properties(eflash_ftl_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/SC17/dhara-master/CMakeLists.txt;156;add_test;E:/SC17/dhara-master/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(eflash_ftl_tests "E:/SC17/dhara-master/build_vs2022/RelWithDebInfo/eflash_ftl_tests.exe")
  set_tests_properties(eflash_ftl_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/SC17/dhara-master/CMakeLists.txt;156;add_test;E:/SC17/dhara-master/CMakeLists.txt;0;")
else()
  add_test(eflash_ftl_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(gentab_test "E:/SC17/dhara-master/build_vs2022/Debug/test_gentab.exe")
  set_tests_properties(gentab_test PROPERTIES  _BACKTRACE_TRIPLES "E:/SC17/dhara-master/CMakeLists.txt;159;add_test;E:/SC17/dhara-master/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(gentab_test "E:/SC17/dhara-master/build_vs2022/Release/test_gentab.exe")
  set_tests_properties(gentab_test PROPERTIES  _BACKTRACE_TRIPLES "E:/SC17/dhara-master/CMakeLists.txt;159;add_test;E:/SC17/dhara-master/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(gentab_test "E:/SC17/dhara-master/build_vs2022/MinSizeRel/test_gentab.exe")
  set_tests_properties(gentab_test PROPERTIES  _BACKTRACE_TRIPLES "E:/SC17/dhara-master/CMakeLists.txt;159;add_test;E:/SC17/dhara-master/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(gentab_test "E:/SC17/dhara-master/build_vs2022/RelWithDebInfo/test_gentab.exe")
  set_tests_properties(gentab_test PROPERTIES  _BACKTRACE_TRIPLES "E:/SC17/dhara-master/CMakeLists.txt;159;add_test;E:/SC17/dhara-master/CMakeLists.txt;0;")
else()
  add_test(gentab_test NOT_AVAILABLE)
endif()
